# Generated by Django 3.2.15 on 2024-02-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='not_same',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='not_me',
        ),
    ]
