# Generated by Django 3.2.16 on 2024-01-28 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20240126_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={
                'verbose_name': 'избранное',
                'verbose_name_plural': 'Избраннoе'},
        ),
        migrations.AlterModelOptions(
            name='ingredientsinrecipe',
            options={'verbose_name': 'количество ингредиентов в рецепте',
                     'verbose_name_plural': 'Количество ингредиентов  в рецепте'},
        ),
        migrations.AlterModelOptions(
            name='tagrecipe',
            options={'verbose_name': 'рецепты и их теги',
                     'verbose_name_plural': 'Рецепты и их теги'},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
    ]
